### ISSUE TITLE
[Feature Request] Navigation addition and word count

### ISSUE THREAD

**Issue by monk-blade** [ping/newsrack#1]
1 . Word count - of article
2. Skip to next article button(or link)
3. Go to Table of Contents button(or link)

**Comment by ping** [comment]
> 1 . Word count - of article 

This is not possible since calibre which generates the ebook does not have this ability.

> 2. Skip to next article button(or link) 
> 3. Go to Table of Contents button(or link)

I'm guessing you're only interested in the epub format. If you modify [_recipes.py](https://github.com/ping/newsrack/blob/main/_recipes.py) `src_ext`, `target_ext` in your fork like shown below, you should get what you want since calibre will generate those navigation items natively for epubs. You will need to enable Pages to deploy from the `gh-pages` branch of your fork.

```python
# change in _recipes.py
Recipe(
    recipe="example",
    slug="example",
    src_ext="epub",    # generate only epub
    target_ext=[],     # don't generate alt formats
    category="example",
)
```

**Comment by monk-blade** [comment]
Sorry for confusion. You have made really great software. It is possible in EPUB. I was referring to MOBI, and can we process html and append word count next to header?

**Comment by ping** [comment]
> Sorry for confusion. You have made really great software. It is possible in EPUB. I was referring to MOBI, 

The mobi format is really only meant for Kindles and I don't know what device you use, but the eInk devices already has those navigation elements built-in. There is no need for them in the mobi.

> and can we process html and append word count next to header?

No.
