### ISSUE TITLE
[bug] screenshot attached

### ISSUE THREAD

**Issue by monk-blade** [ping/newsrack#3]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/1335766/185095557-408f8be5-1aa2-4c3f-9e40-def4e9400cba.png">

**Comment by monk-blade** [comment]
not generating mobi of default recipes(only executes custom recipes)

**Comment by ping** [comment]
1. This is not a bug. It's because you've made the value a string with `"""` https://github.com/monk-blade/newsrack/blob/d76bc83376a3680228f36764409c84e7c38421ed/_recipes.py

2. Recipes defined in `_recipes_custom.py` will completely overwrite the default set. If you want to use any of the default newsrack recipes, just add the recipe definition you want to `_recipes_custom.py`. You don't need to put a copy of the recipe source in `recipes_custom/` ([example](https://github.com/ping/newsrack-fork-test/commit/85df28101edad9126a75c66cc043432b5dd8ef1f)).

I want to highlight that there is a demo fork repository at https://github.com/ping/newsrack-fork-test/ that you can use for reference when customising your instance.

You should leave `_recipes.py` untouched and put your custom list of recipes in `_recipes_custom.py`. Overwriting `_recipes.py` will likely require you to manage conflicts frequently in the future.

The example customisations can be seen here https://github.com/ping/newsrack-fork-test/compare/main...custom

**Comment by monk-blade** [comment]
Ok. Thanks
